name: freeswitch-push-to-gitee

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 */5 * *'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  push-to-gitee:
    if: ${{ (github.repository_owner == 'jingjingxyk') }}
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: |
          sudo apt install openssh-client

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Env
        run: |
          echo "CURRENT_BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - name: Prepare Secret Key
        env:
          PUSH_TO_GITEE_SECRET_KEY: ${{ secrets.PUSH_TO_GITEE_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "$PUSH_TO_GITEE_SECRET_KEY" > ~/.ssh/github-push-to-gitee-key
          chmod 0400 ~/.ssh/github-push-to-gitee-key
          cat > ~/.ssh/config <<'EOF'
          Host gitee.com
            Hostname gitee.com
            Port 22
            PreferredAuthentications publickey
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/github-push-to-gitee-key
          EOF
          ls -lh ~/.ssh/

      - name: push to gitee with git mirror
        run: |
          set -x
          CURRENT_DIR=$(pwd)
          ls -lha .
          # python -m pip install git-filter-repo
          curl -fSLo /usr/local/bin/git-filter-repo https://github.com/newren/git-filter-repo/blob/main/git-filter-repo?raw=ture 
          chmod a+x /usr/local/bin/git-filter-repo

          git remote -v
          git clone --single-branch  --branch master https://github.com/signalwire/freeswitch.git repo
          cd repo
          git-filter-repo --refs master
          git log --oneline 
          git branch -a
          git remote -v 
          git remote set-url gitee git@gitee.com:jingjingxyk/freeswitch.git
          git remote -v

          git push gitee master:master



