name: kamailio-push-to-gitee

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 */5 * *'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  push-to-gitee:
    if: ${{ (github.repository_owner == 'jingjingxyk') }}
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: |
          sudo apt install openssh-client

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Env
        run: |
          echo "CURRENT_BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - name: Prepare Secret Key
        env:
          PUSH_TO_GITEE_SECRET_KEY: ${{ secrets.PUSH_TO_GITEE_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "$PUSH_TO_GITEE_SECRET_KEY" > ~/.ssh/github-push-to-gitee-key
          chmod 0400 ~/.ssh/github-push-to-gitee-key
          cat > ~/.ssh/config <<'EOF'
          Host gitee.com
            Hostname gitee.com
            Port 22
            PreferredAuthentications publickey
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/github-push-to-gitee-key
          EOF
          ls -lh ~/.ssh/

      - name: push to gitee with git mirror
        run: |
          set -x
          CURRENT_DIR=$(pwd)

          git clone -b master --progress https://github.com/kamailio/kamailio.git app
          cd  app
          git remote add gitee git@gitee.com:jingjingxyk/kamailio.git
          git remote -v 

          git for-each-ref --format 'delete %(refname)' refs/
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push gitee master:master
          
          exit 0 
          git clone --mirror https://github.com/kamailio/kamailio.git app
          cd  app
          git remote set-url --push origin git@gitee.com:jingjingxyk/kamailio.git
          git remote -v
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror

          cd ${CURRENT_DIR}

