name: swoole-src-push-to-gitee

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  push-to-gitee:
    if: ${{ (github.repository_owner == 'jingjingxyk') }}
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: |
          sudo apt install openssh-client

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Env
        run: |
          echo "CURRENT_BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - name: Prepare Secret Key
        env:
          PUSH_TO_GITEE_SECRET_KEY: ${{ secrets.PUSH_TO_GITEE_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "$PUSH_TO_GITEE_SECRET_KEY" > ~/.ssh/github-push-to-gitee-key
          chmod 0400 ~/.ssh/github-push-to-gitee-key
          cat > ~/.ssh/config <<'EOF'
          Host gitee.com
            Hostname gitee.com
            Port 22
            PreferredAuthentications publickey
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/github-push-to-gitee-key
          EOF
          ls -lh ~/.ssh/

      - name: push to gitee with git mirror
        run: |
          set -x
          CURRENT_DIR=$(pwd)
          ls -lha .

          git remote -v
          git clone --mirror https://github.com/swoole/swoole-src.git swoole-src
          cd swoole-src
          pwd

          git remote set-url --push origin git@gitee.com:jingjingxyk/swoole-src.git
          git remote -v

          git fetch -p origin
          # Exclude refs created by GitHub for pull request.
          git for-each-ref --sort=-authorname --format='%(committerdate) %(authorname) %(refname)'
          git for-each-ref --format '%(refname)' 
          # git for-each-ref --format '%(refname)' ｜ grep -v 'refs/heads/' | grep -v 'refs/tags/' 
          
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git for-each-ref --format 'delete %(refname)' refs/remotes | git update-ref --stdin
          git for-each-ref --format 'delete %(refname)' refs/for | git update-ref --stdin

          git push --mirror

          cd ${CURRENT_DIR}

          git clone --mirror https://github.com/swoole/phpy.git phpy
          cd phpy
          git remote set-url --push origin git@gitee.com:jingjingxyk/phpy.git
          git remote -v
          git for-each-ref --format 'delete %(refname)' 
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
          
          cd ${CURRENT_DIR}
          
          git clone --mirror https://github.com/swoole/phpx.git phpx
          cd phpx
          git remote set-url --push origin git@gitee.com:jingjingxyk/phpx.git
          git remote -v
          git for-each-ref --format 'delete %(refname)' 
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror